'use client';

import {useEffect,useState,type CSSProperties} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Brain,CalendarDays,Check,CheckCheck,Clock3,Code2,Flame,GraduationCap,MessageSquare} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,XAxis,YAxis} from 'recharts';
import {ChartContainer,ChartTooltip,ChartTooltipContent} from '@/components/ui/chart';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {dashboardStats} from '@/lib/dashboard-data';
import {blocks,dateFromKey,lessons,phases,placementTopics,taskIds,type Lesson,type Session,type StudyState} from '@/lib/study-data';
import {PageHeading,type StudyBlock,type WorkspaceView} from './workspace-panels';

type Props={data:StudyState;today:string;day:number;lesson:Lesson;session:Session;ready:boolean;codingAccepted:number|null;codingDays:string[];labels:Record<string,string[]>;onView:(view:WorkspaceView)=>void;onBlock:(block:StudyBlock|'weekly'|'reflection')=>void;onResource:(id:string)=>void;onToggle:(id:string)=>void;onPhase:(phase:number)=>void};

export function CompletionDial({value,size=128}:{value:number;size?:number}){
  return <div className="completion-dial" style={{width:size,height:size}}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52" className="dial-track"/><circle cx="60" cy="60" r="52" className="dial-value" strokeDasharray={Math.PI*104} strokeDashoffset={Math.PI*104*(1-value/100)}/></svg><div><strong>{value}<small>%</small></strong><span>complete</span></div></div>;
}

export function Dashboard({data,today,day,lesson,session,ready,codingAccepted,codingDays,labels,onView,onBlock,onResource,onToggle,onPhase}:Props){
  const [period,setPeriod]=useState('7'),[motion,setMotion]=useState(false);
  useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
  const stats=dashboardStats(data,today,Number(period),codingDays);
  const checked=taskIds.filter(id=>session.checks.includes(id)).length,percent=Math.round(checked/taskIds.length*100);
  const date=today?dateFromKey(today):null,weekday=date?.getDay()??0,placement=placementTopics[weekday];
  const next=taskIds.find(id=>!session.checks.includes(id));
  const nextBlock=next?.split('-')[0] as StudyBlock|undefined;
  const nextLabel=next&&nextBlock?labels[nextBlock][Number(next.split('-')[1])]:'';
  const metrics=[{icon:Flame,value:stats.streak,label:'Day streak',note:stats.studiedToday?'Today is counted':stats.streak?'Study today to keep it going':'Start your first study day',color:'orange'},
    {icon:Code2,value:codingAccepted??'—',label:'Coding problems accepted',note:'Across all 590 coding exercises',color:'blue'},
    {icon:GraduationCap,value:data.mastered.length,label:'Topics mastered',note:`of ${lessons.length} on your roadmap`,color:'purple'},
    {icon:CalendarDays,value:stats.activeDays,label:`Active days / ${period}`,note:`${stats.tasks} tasks completed`,color:'green'}];
  return <div className="overview-view"><PageHeading eyebrow="MY WORKSPACE / OVERVIEW" title="Let’s make progress." description="Your daily plan and the work you’ve put in."><span className="date-label"><CalendarDays size={17}/>{date?date.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'long'}):'Today’s plan'}</span></PageHeading>
    <div className="overview-start"><section className="today-workspace"><div className="today-workspace-heading"><div><span className="day-marker">DAY {String(day).padStart(2,'0')}</span><h2>Your 60-minute plan</h2></div><button className="text-button" onClick={()=>onView('today')}>Open board <ArrowUpRight size={16}/></button></div><div className="daily-sequence">{blocks.map((block,i)=>{const ids=taskIds.filter(id=>id.startsWith(block.id)),done=ids.every(id=>session.checks.includes(id));return <button key={block.id} className={`sequence-block ${block.color} ${done?'sequence-done':''}`} onClick={()=>onBlock(block.id as StudyBlock)}><span>{done?<Check size={17}/>:String(i+1).padStart(2,'0')}</span><strong>{block.label}</strong><small>{block.minutes} min</small><Progress value={ids.filter(id=>session.checks.includes(id)).length/ids.length*100} aria-label={`${block.label} progress`}/></button>;})}</div><div className="next-task"><span className="next-task-label">{next?'UP NEXT':'CHECKLIST COMPLETE'}</span>{next?<><Checkbox id="overview-next" className="task-checkbox" disabled={!ready} checked={false} onCheckedChange={()=>onToggle(next)}/><label htmlFor="overview-next">{nextLabel}</label><button className="next-task-open" aria-label={`Open ${nextBlock}`} onClick={()=>onBlock(nextBlock!)}><ArrowUpRight size={18}/></button></>:<><CheckCheck size={20}/><span>{session.reported?'Your session and reflection are complete.':'Record what went well and what needs another try.'}</span><button className="text-button" onClick={()=>onBlock('reflection')}>Reflection <ArrowRight size={15}/></button></>}</div></section>
    <section className="daily-score"><div><span>Today’s progress</span><strong>{checked}<small> / {taskIds.length} tasks</small></strong><p>{checked===taskIds.length?'Your daily checklist is complete.':'A small step at a time.'}</p></div><CompletionDial value={percent}/><div className="score-footer"><Clock3 size={15}/><span>1 hour daily goal</span><span className="score-phase">Phase {lesson.phase}</span></div></section></div>
    <div className="overview-metrics">{metrics.map((metric,i)=><div className={`overview-metric ${metric.color}`} key={metric.label} style={{'--delay':`${i*60}ms`} as CSSProperties}><span className="metric-symbol"><metric.icon size={22}/></span><div><span>{metric.label}</span><strong>{ready?metric.value:'—'}</strong><small>{metric.note}</small></div></div>)}</div>
    <StreakCard data={data} today={today} codingDays={codingDays} ready={ready} onCode={()=>onBlock('code')}/>
    <div className="overview-body"><div className="overview-main"><section className="surface activity-surface"><div className="section-heading"><div><h2>Study activity</h2><p>Completed checklist tasks</p></div><ToggleGroup type="single" value={period} onValueChange={v=>{if(v)setPeriod(v);}} className="period-control" aria-label="Activity time range"><ToggleGroupItem value="7" aria-label="Last 7 days">7 days</ToggleGroupItem><ToggleGroupItem value="28" aria-label="Last 28 days">28 days</ToggleGroupItem></ToggleGroup></div><ChartContainer config={{tasks:{label:'Tasks completed',color:'#4566f1'}}} className="activity-chart"><BarChart accessibilityLayer data={stats.activity} margin={{top:15,right:12,left:-20,bottom:0}} barCategoryGap={period==='7'?'35%':'24%'}><CartesianGrid vertical={false} stroke="#e6ebf3" strokeDasharray="4 5"/><XAxis dataKey="date" axisLine={false} tickLine={false} minTickGap={22} tickMargin={13} tickFormatter={v=>dateFromKey(v).toLocaleDateString('en-IN',period==='7'?{weekday:'short'}:{day:'numeric',month:'short'})}/><YAxis domain={[0,9]} ticks={[0,3,6,9]} axisLine={false} tickLine={false}/><ChartTooltip cursor={{fill:'#3659ed07'}} content={<ChartTooltipContent labelFormatter={v=>dateFromKey(String(v)).toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}/>}/><Bar dataKey="tasks" fill="var(--color-tasks)" radius={[6,6,0,0]} maxBarSize={34} isAnimationActive={motion} animationDuration={650}/></BarChart></ChartContainer><div className="surface-footer"><span>{stats.tasks?`${stats.tasks} tasks across ${stats.activeDays} active days`:'Your completed tasks will appear here.'}</span><button className="text-button" onClick={()=>onView('progress')}>View study log <ArrowRight size={15}/></button></div></section>
    <section className="surface roadmap-preview"><div className="section-heading"><div><h2>Your learning path</h2><p>{data.mastered.length} of {lessons.length} topics mastered</p></div><button className="text-button" onClick={()=>onView('roadmap')}>View roadmap <ArrowUpRight size={16}/></button></div><div className="phase-track">{phases.map((phase,i)=>{const items=lessons.filter(l=>l.phase===i+1),count=items.filter(l=>data.mastered.includes(l.id)).length;return <button key={phase.name} className={lesson.phase===i+1?'track-current':''} onClick={()=>onPhase(i+1)} aria-label={`View roadmap, phase ${i+1}: ${phase.name}`}><span>0{i+1}{count===items.length&&<Check size={13}/>}</span><strong>{['Java basics','DSA patterns','Linear structures','Trees','Heaps & graphs','Dynamic programming'][i]}</strong><Progress value={count/items.length*100} aria-label={`${phase.name} progress`}/><small>{count}/{items.length}</small></button>;})}</div></section>
    <section className="surface revision-surface"><div className="section-heading"><div><h2>Revisit & strengthen</h2><p>Your recent revision notes</p></div><Brain size={22}/></div>{stats.revision.length?<div className="revision-list">{stats.revision.map(s=><button key={s.date} onClick={()=>onResource(s.topicId)}><span className="revision-list-icon"><RotateIcon/></span><span><strong>{lessons.find(l=>l.id===s.topicId)?.title}</strong><small>{s.revision||s.notes}</small></span><ArrowUpRight size={17}/></button>)}</div>:<div className="revision-empty"><Brain size={27}/><div><strong>No revision notes yet</strong><p>Use your daily reflection to record what you want to practise again.</p></div><button className="text-button" onClick={()=>onBlock('revision')}>Start revision <ArrowRight size={15}/></button></div>}</section></div>
    <aside className="overview-aside"><section className="current-lesson-card"><div className="lesson-card-label"><BookOpen size={18}/><span>CURRENT TOPIC</span><span>Java</span></div><h2>{lesson.title}</h2><p>{phases[lesson.phase-1].name}</p><span className="level-label">Phase {lesson.phase} · {phases[lesson.phase-1].level}</span><button className="primary-button" onClick={()=>onResource(lesson.id)}>Continue learning <ArrowRight size={16}/></button><button className="secondary-button dashboard-code-button" onClick={()=>onBlock('code')}><Code2 size={17}/>Code · 10 problems <ArrowRight size={15}/></button><span className="source-caption">10 coding problems · concept questions · GFG guide</span></section>
    <section className="surface rotation-surface"><div className="section-heading"><h2>Placement rotation</h2><span>10 min / day</span></div><div className="weekly-rotation">{[1,2,3,4,5,6,0].map(d=><div key={d} className={d===weekday?'rotation-today':''}><span>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]}</span><strong>{placementTopics[d].short}</strong>{d===weekday&&<small>Today</small>}</div>)}</div><button className="rotation-question" onClick={()=>onBlock('placement')}><span><MessageSquare size={17}/>{placement.concept}</span><ArrowUpRight size={17}/></button></section></aside></div>
  </div>;
}
function RotateIcon(){return <BookOpen size={17}/>;}
function StreakCard({data,today,codingDays,ready,onCode}:{data:StudyState;today:string;codingDays:string[];ready:boolean;onCode:()=>void}){
  const stats=dashboardStats(data,today,7,codingDays);
  return <section className={`study-streak-card ${stats.studiedToday?'streak-secured':''}`} aria-label="Daily study streak">
    <div className="streak-count"><span className="streak-flame"><Flame size={26}/></span><div><strong>{ready?stats.streak:'—'} <span>day{stats.streak===1?'':'s'}</span></strong><p>Current study streak</p></div><span className="streak-best">Best: {ready?stats.bestStreak:'—'} days</span></div>
    <div className="streak-calendar"><span>LAST 7 DAYS</span><div>{stats.activity.map(day=><div key={day.date} className={`${day.active?'streak-day-done':''} ${day.date===today?'streak-day-today':''}`} aria-label={`${day.fullLabel}: ${day.active?'study activity saved':'no saved activity'}`}><span>{day.label}</span><i>{day.active?<Check size={17}/>:day.date===today?<Flame size={15}/>:<span/>}</i></div>)}</div></div>
    <div className="streak-next"><strong>{stats.studiedToday?'Today is counted':stats.streak?'Keep your streak going':'Start your first streak'}</strong><p>Save code, complete a study task, or record a reflection each day. Days follow your device’s local date.</p><button className="text-button" disabled={!ready} onClick={onCode}><Code2 size={16}/>{stats.studiedToday?'Continue coding':'Code today'}<ArrowRight size={15}/></button></div>
  </section>;
}
