'use client';
import {lazy,Suspense,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,CheckCheck,ChevronDown,Code2,ExternalLink,Lightbulb,Search} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {lessons,phases,type Lesson} from '@/lib/study-data';
import {gfgUrl,topicResources} from '@/lib/topic-resources';
import {placementResources,type PlacementResource} from '@/lib/placement-resources';
import {PageHeading} from './workspace-panels';
const QuestionPractice=lazy(()=>import('./question-practice'));
function Questions({topicId}:{topicId:string}){return <Suspense fallback={<p className="questions-loading" role="status">Loading your questions…</p>}><QuestionPractice key={topicId} topicId={topicId}/></Suspense>;}

export function TopicLibrary({mastered,currentTopic,onOpen,onPlacement,onQuestions,onPlacementQuestions,onCoding}:{mastered:string[];currentTopic:string;onOpen:(id:string)=>void;onPlacement:(id:string)=>void;onQuestions:(id:string)=>void;onPlacementQuestions:(id:string)=>void;onCoding:(id:string)=>void}){
  const [query,setQuery]=useState(''),[category,setCategory]=useState('dsa'),[phase,setPhase]=useState('all');
  const needle=query.trim().toLowerCase();
  const filtered=lessons.filter(l=>(phase==='all'||l.phase===Number(phase))&&[l.title,...topicResources[l.id].topics].some(t=>t.toLowerCase().includes(needle)));
  const placementFiltered=placementResources.filter(r=>[r.title,r.group,...r.topics].some(t=>t.toLowerCase().includes(needle)));
  const count=category==='dsa'?filtered.length:placementFiltered.length;
  const current=lessons.find(l=>l.id===currentTopic)??lessons[0];
  return <div className="library-view"><PageHeading eyebrow="TOPICS, EXAMPLES & REFERENCES" title="Your learning library" description="Learn each topic, write code for 10 problems, and explore the linked GeeksforGeeks guide."><span className="catalog-total"><BookOpen size={18}/>{lessons.length+placementResources.length} topic guides</span></PageHeading>
    <Tabs value={category} onValueChange={setCategory} className="catalog-workspace"><aside className="catalog-sidebar"><span className="filter-label">BROWSE TOPICS</span><TabsList className="catalog-categories" aria-label="Topic category"><TabsTrigger value="dsa"><Code2 size={17}/>Java & DSA<span>{lessons.length}</span></TabsTrigger><TabsTrigger value="placement"><BookOpen size={17}/>Placement prep<span>{placementResources.length}</span></TabsTrigger></TabsList>{category==='dsa'?<div className="catalog-phases"><span className="filter-label">LEARNING PHASE</span><RadioGroup value={phase} onValueChange={setPhase} aria-label="Filter learning phase"><div><RadioGroupItem id="phase-all" value="all"/><label htmlFor="phase-all">All phases</label><span>{lessons.length}</span></div>{phases.map((p,i)=><div key={p.name}><RadioGroupItem id={`filter-phase-${i}`} value={String(i+1)}/><label htmlFor={`filter-phase-${i}`}><strong>Phase {i+1}</strong><small>{['Java foundations','Core patterns','Lists & recursion','Trees & traversal','Heaps & graphs','Dynamic programming'][i]}</small></label><span>{lessons.filter(l=>l.phase===i+1).length}</span></div>)}</RadioGroup></div>:<div className="catalog-help"><h3>One topic each day</h3><p>Use the weekly rotation for your 10-minute placement block. Keep the remaining references handy for revision.</p></div>}<div className="gfg-sidebar-note"><span className="gfg-badge">GFG</span><strong>Read. Try. Understand.</strong><p>Every guide includes a direct GeeksforGeeks reference.</p></div></aside>
    <TabsContent value={category} className="catalog-main" key={category}><div className="catalog-search"><Search size={20}/><Input type="search" aria-label="Search topics and concepts" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a topic, concept, or technique…"/><span>{count} topics</span></div>{category==='dsa'&&!needle&&phase==='all'&&<div className="catalog-continue"><span className="catalog-continue-icon"><BookOpen size={24}/></span><div><span>YOUR CURRENT TOPIC</span><strong>{current.title}</strong></div><button className="secondary-button" onClick={()=>onOpen(current.id)}>Continue lesson <ArrowRight size={16}/></button></div>}<div className="catalog-list-heading"><h2>{category==='dsa'?(phase==='all'?'Java & DSA topics':phases[Number(phase)-1].name):'Placement topics'}</h2><span>{needle?`Results for “${query}”`:category==='dsa'?'Follow your phase order':'Reference collection'}</span></div>
    {!count?<Empty className="empty-state"><EmptyHeader><EmptyMedia><Search size={28}/></EmptyMedia><EmptyTitle>No matching topics</EmptyTitle><EmptyDescription>Try another word or clear the phase filter.</EmptyDescription></EmptyHeader><button className="secondary-button" onClick={()=>{setQuery('');setPhase('all');}}>Clear filters</button></Empty>:<div className="catalog-list">{category==='dsa'?filtered.map((lesson,index)=>{const resource=topicResources[lesson.id];return <article className="catalog-row" key={lesson.id}><span className={`catalog-row-number ${mastered.includes(lesson.id)?'mastered':''}`}>{mastered.includes(lesson.id)?<CheckCheck size={19}/>:String(index+1).padStart(2,'0')}</span><div className="catalog-topic"><button onClick={()=>onOpen(lesson.id)}>{lesson.title}</button><p>{resource.topics.slice(0,3).join(' · ')}</p><span>Phase {lesson.phase} · {phases[lesson.phase-1].level}</span></div><div className="catalog-row-actions"><button className="catalog-questions catalog-code" onClick={()=>onCoding(lesson.id)} aria-label={`Open 10 coding problems for ${lesson.title}`}><Code2 size={14}/>Code · 10</button><button className="catalog-questions" onClick={()=>onQuestions(lesson.id)} aria-label={`Practise 10 questions on ${lesson.title}`}>Concept questions <ArrowRight size={13}/></button><a className="gfg-inline" href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer" aria-label={`Read ${lesson.title} on GeeksforGeeks`}>GeeksforGeeks <ExternalLink size={14}/></a><button className="catalog-open" onClick={()=>onOpen(lesson.id)} aria-label={`Open ${lesson.title} lesson`}><ArrowUpRight size={19}/></button></div></article>;}):placementFiltered.map((resource,index)=><article className="catalog-row" key={resource.id}><span className="catalog-row-number">{String(index+1).padStart(2,'0')}</span><div className="catalog-topic"><button onClick={()=>onPlacement(resource.id)}>{resource.title}</button><p>{resource.topics.join(' · ')}</p><span>{resource.day} · {resource.group}</span></div><div className="catalog-row-actions"><button className="catalog-questions catalog-code" onClick={()=>onCoding(resource.id)} aria-label={`Open 10 coding problems for ${resource.title}`}><Code2 size={14}/>Code · 10</button><button className="catalog-questions" onClick={()=>onPlacementQuestions(resource.id)} aria-label={`Practise 10 questions on ${resource.title}`}>Concept questions <ArrowRight size={13}/></button><a className="gfg-inline" href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer" aria-label={`Read ${resource.referenceLabel??resource.title} on GeeksforGeeks`}>GeeksforGeeks <ExternalLink size={14}/></a><button className="catalog-open" onClick={()=>onPlacement(resource.id)} aria-label={`Open ${resource.title} guide`}><ArrowUpRight size={19}/></button></div></article>)}</div>}</TabsContent></Tabs>
  </div>;
}
export function TopicLesson({ lesson, initialTab='concept', onCoding }: {
    lesson: Lesson; initialTab?: 'concept'|'questions'; onCoding?:()=>void;
}) {
    const resource = topicResources[lesson.id];
    return <div className="topic-lesson">{onCoding&&<button className="lesson-code-shortcut" onClick={onCoding}><span><Code2 size={20}/><span><strong>10 coding problems for this topic</strong><small>3 Easy · 4 Medium · 3 Hard · Write and run Java</small></span></span><span>Code in Java <ArrowRight size={16}/></span></button>}<Tabs defaultValue={initialTab} key={`${lesson.id}-${initialTab}`} className="lesson-reader"><TabsList className="reader-tabs" aria-label="Lesson sections"><TabsTrigger value="concept">01 · Concept</TabsTrigger><TabsTrigger value="example">02 · Worked example</TabsTrigger><TabsTrigger value="questions">03 · Concept questions (10)</TabsTrigger></TabsList><TabsContent value="concept" className="reader-panel"><div className="concept-chips lesson-chips">{resource.topics.map(topic => <span key={topic}>{topic}</span>)}</div>
    <section className="lesson-section"><h3>In simple words</h3><p>{lesson.definition}</p></section>
    <section className="lesson-section"><h3>Why you’ll use it</h3><p>{resource.use}</p></section>
    <section className="lesson-section"><div className="code-window-label"><span><i /><i /><i />Java concept snippet</span><span>JAVA</span></div><pre><code>{lesson.exampleCode}</code></pre><p className="small-note">A separate practice illustration. Place statements inside a method and methods inside a class. Add java.util imports for collections and Scanner; algorithm sketches assume the named inputs exist.</p></section>
    <section className="complexity-box"><span><Code2 size={18}/></span><div><h3>Time & space complexity</h3><p>{lesson.complexity}</p></div></section>
    </TabsContent><TabsContent value="example" className="reader-panel"><section className="worked-example"><div className="worked-example-heading"><span><Lightbulb size={17}/>WORKED EXAMPLE</span><a href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer">GeeksforGeeks <ExternalLink size={13}/></a></div><h3>{resource.exampleTitle}</h3><div className="example-input"><span>Start with</span><p>{resource.input}</p></div><details className="example-reveal"><summary>Think it through, then reveal the walkthrough <ChevronDown size={16}/></summary><div><span className="example-output-label">RESULT</span><strong>{resource.output}</strong><p>{resource.explanation}</p></div></details><p className="example-attribution">Adapted from the linked GeeksforGeeks topic; wording and sample values are simplified for this lesson.</p></section>
    </TabsContent><TabsContent value="questions" className="reader-panel"><Questions topicId={lesson.id}/>
    </TabsContent></Tabs><a className="gfg-source-link" href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer"><span className="gfg-badge">GFG</span><span><strong>Read the full GeeksforGeeks lesson</strong><small>{lesson.title} · explanation, examples and further reading</small></span><ArrowUpRight size={20}/></a>
    {resource.related?.map(link => <a className="text-button related-gfg" key={link.path} href={gfgUrl(link.path)} target="_blank" rel="noopener noreferrer">{link.label} on GeeksforGeeks <ExternalLink size={14}/></a>)}
  </div>;
}
export function PlacementLesson({ resource, initialTab='concept',onCoding }: {
    resource: PlacementResource; initialTab?: 'concept'|'questions'; onCoding?:()=>void;
}) {
    return <div className="topic-lesson">{onCoding&&<button className="lesson-code-shortcut" onClick={onCoding}><span><Code2 size={20}/><span><strong>10 coding problems for this topic</strong><small>3 Easy · 4 Medium · 3 Hard · {resource.id==='sql'?'Write SQL queries':'Build practical Java programs'}</small></span></span><span>Code <ArrowRight size={16}/></span></button>}<Tabs defaultValue={initialTab} key={`${resource.id}-${initialTab}`} className="lesson-reader"><TabsList className="reader-tabs" aria-label="Placement guide sections"><TabsTrigger value="concept">01 · Guide</TabsTrigger><TabsTrigger value="questions">02 · Concept questions (10)</TabsTrigger></TabsList><TabsContent value="concept" className="reader-panel"><div className="concept-chips lesson-chips">{resource.topics.map(t => <span key={t}>{t}</span>)}</div><section className="lesson-section"><h3>The concept</h3><p>{resource.definition}</p></section><section className="worked-example"><div className="worked-example-heading"><span><Lightbulb size={17}/>A PRACTICAL EXAMPLE</span><a href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer">GeeksforGeeks <ExternalLink size={13}/></a></div><p className="placement-example-text">{resource.example}</p><p className="example-attribution">{resource.exampleNote??'A simplified example adapted from the linked topic.'}</p></section><section className="lesson-section"><h3>Try answering aloud</h3><p>{resource.question}</p></section></TabsContent><TabsContent value="questions" className="reader-panel"><Questions topicId={resource.id}/></TabsContent></Tabs><a className="gfg-source-link" href={gfgUrl(resource.path)} target="_blank" rel="noopener noreferrer"><span className="gfg-badge">GFG</span><span><strong>Continue on GeeksforGeeks</strong><small>{resource.referenceLabel??resource.title}</small></span><ArrowUpRight size={20}/></a></div>;
}
