'use client';

import {useState, type CSSProperties} from 'react';
import {ArrowRight, ArrowUpRight, BookOpen, Brain, Braces, CalendarDays, Check, CheckCheck, Clock3, Code2, Copy, Flame, GraduationCap, LayoutDashboard, Lightbulb, ListChecks, Loader2, Map, MessageSquare, Pause, Play, RotateCcw, BarChart3, ExternalLink} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Empty,EmptyDescription,EmptyHeader,EmptyMedia,EmptyTitle} from '@/components/ui/empty';
import {blocks,dateFromKey,isComplete,lessons,phases,placementTopics,taskIds,type Lesson,type Session,type StudyState} from '@/lib/study-data';
import {gfgUrl,topicResources} from '@/lib/topic-resources';
import {dashboardStats} from '@/lib/dashboard-data';
import {AccountMenu} from './account-menu';

export type WorkspaceView='dashboard'|'today'|'coding'|'roadmap'|'library'|'progress';
export type StudyBlock='revision'|'learn'|'code'|'placement';
export const workspaceNavigation=[
  {id:'dashboard',label:'Overview',icon:LayoutDashboard},{id:'today',label:'My day',icon:ListChecks},
  {id:'coding',label:'Coding',icon:Code2},
  {id:'roadmap',label:'Roadmap',icon:Map},{id:'library',label:'Learn',icon:BookOpen},
  {id:'progress',label:'Progress',icon:BarChart3},
] as const;

export function WorkspaceHeader({saveStatus,onHome}:{saveStatus:string;onHome:()=>void}){
  return <header className="workspace-header"><div className="header-inner">
    <button className="wordmark" onClick={onHome} aria-label="Placement Path overview"><span className="wordmark-icon"><Braces size={23}/></span><span>placement<span>path</span><i/></span></button>
    <TabsList className="workspace-navigation" aria-label="Workspace navigation">{workspaceNavigation.map(item=><TabsTrigger key={item.id} value={item.id}><item.icon size={17}/><span>{item.label}</span></TabsTrigger>)}</TabsList>
    <div className="header-account"><span className={`save-indicator status-${saveStatus}`} aria-live="polite">{saveStatus==='loading'||saveStatus==='saving'?<Loader2 size={15} className="spin"/>:saveStatus==='saved'?<CheckCheck size={16}/>:<RotateCcw size={15}/>}<span>{saveStatus==='saved'?'Saved':saveStatus==='loading'?'Loading':saveStatus==='saving'?'Saving':'Save error'}</span></span><AccountMenu/></div>
  </div></header>;
}

export function PageHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:React.ReactNode}){
  return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{children}</div>;
}

export function TodayBoard({day,today,lesson,session,labels,ready,onToggle,onBlock,onFocus,onReflection}:{day:number;today:string;lesson:Lesson;session:Session;labels:Record<string,string[]>;ready:boolean;onToggle:(id:string)=>void;onBlock:(id:StudyBlock)=>void;onFocus:(id:string)=>void;onReflection:()=>void}){
  const icons=[Brain,BookOpen,Code2,MessageSquare];
  const titles=['Recall & revise','Learn the concept','Write some Java','Interview practice'];
  const count=taskIds.filter(id=>session.checks.includes(id)).length;
  const placement=placementTopics[today?dateFromKey(today).getDay():0];
  return <div className="day-view"><PageHeading eyebrow={`DAY ${String(day).padStart(2,'0')} / DAILY WORKSPACE`} title="Today’s study board" description={lesson.title}><span className="date-label"><CalendarDays size={17}/>{today?dateFromKey(today).toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'long'}):'Your daily session'}</span></PageHeading>
    <div className="board-toolbar"><div><span className="board-mode"><ListChecks size={17}/>Daily checklist</span><span className="toolbar-divider"/><span><Clock3 size={16}/>60 minutes planned</span></div><div className="board-completion"><span><strong>{count}</strong> of {taskIds.length} done</span><Progress value={count/taskIds.length*100} aria-label="Daily checklist progress"/></div></div>
    <div className="session-board">{blocks.map((block,i)=>{const Icon=icons[i],done=labels[block.id].filter((_,j)=>session.checks.includes(`${block.id}-${j}`)).length;return <section key={block.id} className={`board-column ${block.color} ${done===labels[block.id].length?'column-complete':''}`} style={{'--delay':`${i*70}ms`} as CSSProperties}><div className="column-heading"><span><i/>0{i+1} · {block.label}</span><span>{done}/{labels[block.id].length}</span></div><article className="board-card"><div className="board-card-top"><span className="board-icon"><Icon size={23}/></span><span className="duration-chip">{block.minutes} min</span></div><h2>{titles[i]}</h2><p>{block.id==='learn'?lesson.title:block.id==='placement'?placement.concept:block.id==='code'?phases[lesson.phase-1].level:'Build on your last session'}</p><div className="board-tasks">{labels[block.id].map((text,j)=>{const id=`${block.id}-${j}`,checked=session.checks.includes(id);return <div className={`task-row ${checked?'task-done':''}`} key={id}><Checkbox className="task-checkbox" id={`board-${id}`} checked={checked} disabled={!ready} onCheckedChange={()=>onToggle(id)}/><label htmlFor={`board-${id}`}>{text}</label>{checked&&<Check size={14} className="completed-check"/>}</div>;})}</div><button className="board-open" onClick={()=>onBlock(block.id as StudyBlock)}>{block.id==='code'?'Open coding workspace':block.id==='learn'?'Open lesson & example':block.id==='revision'?'Open revision questions':'Open interview question'}<ArrowUpRight size={16}/></button></article><button className="block-focus" disabled={!ready} onClick={()=>onFocus(block.id)}><Play size={14}/>Focus for {block.minutes} minutes</button></section>;})}</div>
    <button className={`reflection-banner ${session.reported?'is-complete':''}`} onClick={onReflection} disabled={!ready}><span className="reflection-symbol">{session.reported?<CheckCheck size={23}/>:<MessageSquare size={23}/>}</span><span><strong>{session.reported?'Your reflection is saved':'Finish with a quick reflection'}</strong><small>{session.reported?'Open your answers and revision notes.':'Five answers to help you plan tomorrow.'}</small></span><span className="reflection-action">{session.reported?'View reflection':'Add reflection'}<ArrowRight size={17}/></span></button>
    <div className="board-guidance"><Lightbulb size={17}/><p>Try the coding problem yourself first. Explain your approach, then use one hint at a time.</p></div>
  </div>;
}

export function FocusDock({activeBlock,remaining,running,ready,onChoose,onStartPause,onReset,onCoach,compact=false}:{compact?:boolean;activeBlock:string;remaining:number;running:boolean;ready:boolean;onChoose:(id:string)=>void;onStartPause:()=>void;onReset:()=>void;onCoach:()=>void}){
  const block=blocks.find(b=>b.id===activeBlock)??blocks[2];
  const progress=(1-remaining/(block.minutes*60))*100;
  return <section className={`focus-dock ${running?'dock-running':''}`} aria-label="Focus timer"><div className="dock-progress" style={{'--elapsed':`${progress}%`} as CSSProperties}/><div className="dock-label"><span className="dock-icon"><Clock3 size={21}/></span><div><strong>Focus session</strong><span>{running?'Timer running':remaining===0?'Block complete':'Ready when you are'}</span></div></div><Select value={activeBlock} onValueChange={onChoose} disabled={running||!ready}><SelectTrigger aria-label="Choose focus block" className="dock-select"><SelectValue/></SelectTrigger><SelectContent>{blocks.map(b=><SelectItem key={b.id} value={b.id}>{b.label} · {b.minutes} min</SelectItem>)}</SelectContent></Select><span className="dock-time" role="timer" aria-label={`${Math.floor(remaining/60)} minutes ${remaining%60} seconds remaining`}>{String(Math.floor(remaining/60)).padStart(2,'0')}<i>:</i>{String(remaining%60).padStart(2,'0')}</span><div className="dock-actions"><button className="primary-button" onClick={onStartPause} disabled={!ready}>{running?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}{running?'Pause':remaining<block.minutes*60&&remaining>0?'Resume':compact?'Start':'Start timer'}</button><button className="icon-button" onClick={onReset} disabled={!ready} aria-label="Reset focus timer"><RotateCcw size={18}/></button></div><button className="dock-coach" aria-label="Ask your coach" onClick={onCoach} disabled={!ready}><MessageSquare size={18}/><span>Ask your coach</span><Copy size={14}/></button></section>;
}

export function LearningRoadmap({lesson,queued,mastered,ready,onToggle,onNext,onOpen,onCoding,initialPhase}:{onCoding:(id:string)=>void;initialPhase?:number;lesson:Lesson;queued:string;mastered:string[];ready:boolean;onToggle:(id:string,done:boolean)=>void;onNext:(id:string)=>void;onOpen:(id:string)=>void}){
  const [phase,setPhase]=useState(String(initialPhase??lesson.phase));
  const selected=phases[Number(phase)-1],items=lessons.filter(l=>l.phase===Number(phase)),done=items.filter(l=>mastered.includes(l.id)).length;
  return <div><PageHeading eyebrow="YOUR CURRICULUM" title="A clear path forward" description="Build one topic at a time. Revisit it until you can explain it and code it."><span className="mastery-label"><GraduationCap size={19}/><strong>{mastered.length}</strong> / {lessons.length} mastered</span></PageHeading>
    <Tabs value={phase} onValueChange={setPhase} className="roadmap-workspace"><TabsList className="phase-navigation" aria-label="Learning phase">{phases.map((p,i)=>{const topics=lessons.filter(l=>l.phase===i+1),n=topics.filter(l=>mastered.includes(l.id)).length;return <TabsTrigger value={String(i+1)} key={p.name}><span className="phase-index">{String(i+1).padStart(2,'0')}</span><span><strong>{p.name}</strong><small>{n}/{topics.length} topics · {p.level}</small></span>{n===topics.length&&<Check size={16}/>}</TabsTrigger>;})}</TabsList><TabsContent value={phase} className="phase-workspace" key={phase}><div className="phase-workspace-heading"><div><span className="eyebrow">PHASE {phase} / {selected.level.toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.caption}</p></div><span className="phase-fraction">{done}<small>/{items.length}</small></span></div><Progress className="phase-progress" value={done/items.length*100} aria-label={`${selected.name} mastery`}/><div className="curriculum-list">{items.map((item,i)=><div className={`curriculum-row ${item.id===lesson.id?'current-lesson':''}`} key={item.id}><Checkbox id={`mastery-${item.id}`} className="task-checkbox" checked={mastered.includes(item.id)} disabled={!ready} onCheckedChange={value=>onToggle(item.id,value===true)}/><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><label htmlFor={`mastery-${item.id}`}><strong>{item.title}</strong><small>{topicResources[item.id].topics.slice(0,3).join(' · ')}</small></label><div className="curriculum-actions">{item.id===lesson.id?<span className="status-pill current">Studying</span>:queued===item.id?<span className="status-pill">Up next</span>:<button className="text-button" disabled={!ready} onClick={()=>onNext(item.id)}>Study next</button>}<a className="roadmap-gfg" href={gfgUrl(topicResources[item.id].path)} target="_blank" rel="noopener noreferrer" aria-label={`Read ${item.title} on GeeksforGeeks`}>GFG <ExternalLink size={13}/></a><button className="lesson-open roadmap-code-button" onClick={()=>onCoding(item.id)} aria-label={`Code 10 problems on ${item.title}`}><Code2 size={16}/><span>Code</span></button><button className="lesson-open" onClick={()=>onOpen(item.id)} aria-label={`Open ${item.title} lesson`}><BookOpen size={16}/><span>Lesson</span></button></div></div>)}</div></TabsContent></Tabs>
  </div>;
}

export function ProgressView({data,today,onToday,onWeekly}:{data:StudyState;today:string;onToday:()=>void;onWeekly:()=>void}){
  const sessions=Object.values(data.sessions).filter(s=>s.date<=today).sort((a,b)=>b.date.localeCompare(a.date));
  const stats=dashboardStats(data,today),complete=sessions.filter(isComplete).length;
  return <div><PageHeading eyebrow="YOUR STUDY HISTORY" title="Progress you can see" description="Your sessions, problem attempts, and notes for the next revision."><button className="secondary-button" onClick={onWeekly}><CalendarDays size={17}/>Weekly review</button></PageHeading>
    <div className="history-summary"><div><span className="summary-icon blue"><CheckCheck size={21}/></span><span><strong>{complete}</strong><small>Completed checklists</small></span></div><div><span className="summary-icon green"><Code2 size={21}/></span><span><strong>{stats.solved}<em>{stats.independent} without help</em></strong><small>Problems solved</small></span></div><div><span className="summary-icon purple"><GraduationCap size={21}/></span><span><strong>{data.mastered.length}<em>of {lessons.length}</em></strong><small>Topics mastered</small></span></div></div>
    <section className="history-workspace"><div className="section-heading"><h2>Session log</h2><span>{sessions.length} recorded {sessions.length===1?'day':'days'}</span></div>{!sessions.length?<Empty className="empty-state"><EmptyHeader><EmptyMedia><CalendarDays size={31}/></EmptyMedia><EmptyTitle>Your first session starts here</EmptyTitle><EmptyDescription>Check off a task and save a reflection. Your study history will appear here.</EmptyDescription></EmptyHeader><button className="primary-button" onClick={onToday}>Open today’s board <ArrowRight size={16}/></button></Empty>:<Table className="history-table"><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Topic</TableHead><TableHead>Checklist</TableHead><TableHead>Attempted</TableHead><TableHead>Solved</TableHead><TableHead>Without help</TableHead><TableHead>Notes</TableHead></TableRow></TableHeader><TableBody>{sessions.map(s=><TableRow key={s.date}><TableCell><strong>{dateFromKey(s.date).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</strong><small>{dateFromKey(s.date).getFullYear()}</small></TableCell><TableCell><strong>{lessons.find(l=>l.id===s.topicId)?.title}</strong><small>{placementTopics[dateFromKey(s.date).getDay()].short}</small></TableCell><TableCell><span className={`status-pill ${isComplete(s)?'complete':''}`}>{s.checks.length}/{taskIds.length} {isComplete(s)?'complete':'tasks'}</span></TableCell><TableCell>{s.attempted}</TableCell><TableCell>{s.solved}</TableCell><TableCell>{s.independent}</TableCell><TableCell><details className="log-notes"><summary>{s.notes||s.revision?'View notes':s.reported?'Reflection saved':'No reflection'}</summary><div><strong>Weak area</strong><p>{s.notes||'No difficulty recorded.'}</p><strong>Revision needed</strong><p>{s.revision||'No revision note yet.'}</p></div></details></TableCell></TableRow>)}</TableBody></Table>}</section>
  </div>;
}

