export type PlacementResource = {
    id: string;
    title: string;
    group: string;
    day: string;
    path: string;
    topics: string[];
    definition: string;
    example: string;
    question: string;
    exampleNote?: string;
    referenceLabel?: string;
};
export const placementResources: PlacementResource[] = [
    { id: 'percentages', title: 'Percentages', group: 'Aptitude', day: 'Monday', path: 'maths/percentage', topics: ['Part / whole', 'Percentage change', 'Successive changes'], definition: 'A percentage expresses a quantity out of one hundred.', example: '5% of 50 is (5 / 100) × 50 = 2.5. For a percentage increase, divide the increase by the original value.', question: 'A price rises from 80 to 100. What is the percentage increase?' },
    { id: 'ratio', title: 'Ratio & proportion', group: 'Aptitude', day: 'Monday', path: 'maths/ratio-and-proportion', topics: ['Equivalent ratios', 'Proportion', 'Sharing a total'], definition: 'A ratio compares quantities. A proportion states that two ratios are equal.', example: '50:60 and 100:120 both simplify to 5:6. The actual quantities differ even though the relative comparison is the same.', question: 'Split 120 in the ratio 2:3. How much does each part receive?' },
    { id: 'average', title: 'Average', group: 'Aptitude', day: 'Monday', path: 'aptitude/average', topics: ['Arithmetic mean', 'Combined averages', 'Missing values'], definition: 'The arithmetic average is the total of the values divided by their count.', example: 'For 3, 4, 7, 8, 10 and 12, the total is 44 and the count is 6. Their average is 44/6, about 7.33.', question: 'Five scores average 20. What total do the scores have?' },
    { id: 'profit', title: 'Profit & loss', group: 'Aptitude', day: 'Monday', path: 'aptitude/profit-loss', topics: ['Cost & selling price', 'Profit percentage', 'Discount'], definition: 'Profit occurs when the selling price exceeds cost. Loss occurs when it is below cost.', example: 'An item bought for 100 and sold for 120 earns 20 profit. Profit percentage is 20/100 × 100 = 20%. Use cost as the denominator.', question: 'An item costs 400 and sells for 340. What is the loss percentage?' },
    { id: 'work', title: 'Time & work', group: 'Aptitude', day: 'Monday', path: 'aptitude/time-work-and-wages', topics: ['Work rates', 'Combined work', 'Efficiency'], definition: 'Work done equals the rate of work multiplied by the time spent.', example: 'If A completes a job in 10 days and B in 15, their daily rates are 1/10 and 1/15. Together, their rate is 1/6 of the job per day, assuming constant independent rates.', question: 'If one worker takes 8 days and another takes 8 days, how long do they take together?' },
    { id: 'speed', title: 'Speed, time & distance', group: 'Aptitude', day: 'Monday', path: 'aptitude/speed-time-distance', topics: ['Units', 'Relative speed', 'Average speed'], definition: 'Speed is the distance traveled per unit of time. Keep the units consistent.', example: 'Traveling 150 km in 3 hours gives a speed of 50 km/h. For several legs, average speed is total distance divided by total time.', question: 'Convert 72 km/h into meters per second.' },
    { id: 'probability', title: 'Probability', group: 'Aptitude', day: 'Monday', path: 'maths/basic-concepts-of-probability', topics: ['Sample space', 'Events', 'Independent events'], definition: 'Probability measures how likely an event is, from 0 to 1. Counting favorable outcomes works when outcomes are equally likely.', example: 'A fair six-sided die has three even outcomes: 2, 4 and 6. The probability of an even roll is 3/6 = 1/2.', question: 'What is the probability of exactly one head in two independent fair coin tosses?' },
    { id: 'logical', title: 'Logical reasoning', group: 'Aptitude', day: 'Monday', path: 'aptitude/number-series-in-quantitative-aptitude', topics: ['Number series', 'Differences', 'Alternating patterns'], definition: 'Look for a consistent relationship and check that it explains the entire given sequence.', example: 'For 3, 6, 9, 12, consecutive differences are all 3. Under that arithmetic pattern, the next term is 15.', question: 'Explain the intended pattern in 2, 4, 8, 16. What term follows?' },
    { id: 'dbms', title: 'DBMS: keys & relationships', group: 'DBMS', day: 'Tuesday', path: 'dbms/difference-between-primary-key-and-foreign-key', topics: ['Primary key', 'Foreign key', 'Referential integrity'], definition: 'A primary key uniquely identifies a row. A foreign key connects rows by referencing a key in another table.', example: 'Student.student_id identifies a student. Enrollment.student_id can reference it, letting one student have several enrollment rows while keeping the relationship valid.', question: 'Can a foreign key column contain duplicate values?' },
    { id: 'os', title: 'OS: processes & threads', group: 'Operating systems', day: 'Wednesday', path: 'operating-systems/difference-between-process-and-thread', topics: ['Address space', 'Shared memory', 'Context switches'], definition: 'A process is a running program with its own address space. Threads are execution paths inside a process.', example: 'Two threads in one application can access shared process data, but each has its own stack. Updating the same counter requires coordination to avoid a race.', question: 'Which resources do threads share, and which are private to each thread?' },
    { id: 'networks', title: 'Networks: TCP & UDP', group: 'Computer networks', day: 'Thursday', path: 'computer-networks/differences-between-tcp-and-udp', topics: ['Reliability', 'Ordering', 'Datagrams'], definition: 'TCP delivers an ordered reliable byte stream. UDP sends individual datagrams without delivery or ordering guarantees.', example: 'A file transfer needs all its bytes in order. A live voice application may prefer timely packets and tolerate some loss. An application using UDP can add reliability itself.', question: 'Why might real-time applications use UDP? What trade-off does that introduce?' },
    { id: 'java-interview', title: 'Java interview: encapsulation', group: 'Java & OOP', day: 'Friday', path: 'java/encapsulation-in-java', topics: ['Private fields', 'Controlled access', 'Validation'], definition: 'Encapsulation keeps data and the behavior that manages it together, with controlled access to internal state.', example: 'A class can keep a name private and expose getter and setter methods. A setter can validate input before changing the stored value.', question: 'Why might a class expose a getter without exposing a setter?' },
    { id: 'sql', title: 'SQL: SELECT & WHERE', group: 'SQL', day: 'Saturday', path: 'sql/sql-where-clause', topics: ['Column selection', 'Row filtering', 'Comparisons'], definition: 'SELECT chooses the columns to return; WHERE filters the rows that qualify.', example: 'SELECT name FROM students WHERE marks > 80; returns only the names of students whose marks exceed 80. A score of exactly 80 is excluded.', question: 'How would you include rows whose marks equal 80 as well?' },
    { id: 'hr', title: 'HR & project storytelling', group: 'Interview skills', day: 'Sunday', path: 'hr/hr-interview-questions', topics: ['Self-introduction', 'Personal contribution', 'Concrete evidence'], definition: 'A clear interview answer connects your background, what you have built and what you learned.', example: 'Use a short structure: “I am studying… I built… My contribution was… One challenge I handled was…” Replace every prompt with your actual experience.', question: 'Tell me about yourself and one project that demonstrates a relevant skill.' },
    { id: 'resume', title: 'Resume: make your work clear', group: 'Career preparation', day: 'Sunday', path: 'hr/hr-interview-questions', referenceLabel: 'HR interview preparation', topics: ['Relevant skills', 'Evidence-based bullets', 'Personal contribution', 'Role fit'], definition: 'A placement resume makes your relevant skills and work easy to assess. Each claim should connect to something you can explain or demonstrate.', example: 'Turn “Worked on a project” into “Implemented [your feature] to help [user] complete [workflow].” Fill the placeholders with your own work. Add measured results only when you have a reliable baseline and evidence.', exampleNote: 'An original resume-writing exercise. The GFG link is a general HR interview reference.', question: 'Which resume bullet best demonstrates a skill needed for your target role, and what evidence supports it?' },
    { id: 'github', title: 'GitHub: present a runnable project', group: 'Career preparation', day: 'Sunday', path: 'git/what-is-readme-md-file', referenceLabel: 'README.md files', topics: ['README', 'Setup & usage', 'Commits & pull requests', 'Contribution evidence'], definition: 'A useful repository lets another person understand, run, and review your project. Its README connects the problem, setup instructions, usage, and implementation.', example: 'Introduce the project and intended users, list prerequisites and setup commands, then show one sample workflow and its expected result. Include configuration variable names with safe example values, never real credentials.', exampleNote: 'An original portfolio checklist, with a GeeksforGeeks reference explaining README structure.', question: 'Can a reviewer reproduce one important workflow from your README without asking you for missing steps?' },
    { id: 'flocksense', title: 'FlockSense: project interview', group: 'Project explanation', day: 'Sunday', path: 'hr/hr-interview-questions', referenceLabel: 'HR & project storytelling', topics: ['Problem & architecture', 'Data & algorithms', 'AI/ML evidence', 'Novelty & impact'], definition: 'Explain FlockSense through the livestock-monitoring problem, the user journey, your own contribution, and one working data flow. Connect every claimed feature to actual implementation evidence.', example: 'Use this pitch outline: “The user difficulty was… I implemented… A reading moves from… to… One challenge was… We verified it by…” Identify rule-based logic as rule-based, and name a trained model only if it was actually trained and evaluated.', exampleNote: 'An original project preparation framework. Hypothetical question scenarios are practice designs, not claims about your implementation. GFG supplies a general interview reference.', question: 'Trace one FlockSense observation from entry to storage and display or alert, then explain one limitation honestly.' },
    { id: 'flowpulse', title: 'FlowPulse: project interview', group: 'Project explanation', day: 'Sunday', path: 'hr/hr-interview-questions', referenceLabel: 'HR & project storytelling', topics: ['Patient-flow problem', 'Queue & state design', 'Concurrency', 'Evaluation & improvements'], definition: 'Explain FlowPulse through the queue-management difficulty, the roles using it, and the lifecycle of one ticket. State how your actual code selects and updates tickets, then discuss its limitations.', example: 'Demonstrate a synthetic ticket moving from waiting through service to completion. Show where validation, storage, and UI updates happen. Discuss a real challenge such as retries or simultaneous updates, and distinguish measured outcomes from planned improvements.', exampleNote: 'An original project preparation framework. The practice scenarios do not assume particular technologies, deployed features, or measured results. GFG supplies a general interview reference.', question: 'How does your implemented queue behave when two staff members act at once, and what would you improve next?' },
];
export const dailyPlacementResourceIds = ['hr', 'percentages', 'dbms', 'os', 'networks', 'java-interview', 'sql'];
