export type Lesson = {id:string;title:string;phase:number;definition:string;exampleCode:string;complexity:string;problem:string;example:string;hint:string;};
type Row=[string,string,number,string,string,string,string,string,string];
const rows:Row[]=[
['variables','Variables & data types',1,'A variable is a named place to keep a value. Its type tells Java what it can hold. Use int for whole-number counts, double for decimals, boolean for true/false, and String for text. A farm can store its bird count and farm name separately.','int birds = 120;\ndouble temperature = 29.5;\nboolean needsReview = false;\nString farmName = "Green Farm";\nSystem.out.println(birds);','These fixed declarations take O(1) time and O(1) auxiliary space.','Store and display a student profile','Create variables for a name, age, daily practice hours and placement eligibility. Print each with a label. Try age 20, hours 1.5 and eligible true.','Choose each value’s type first. Text uses double quotes; boolean values do not.'],
['operators','Arithmetic operators',1,'Operators calculate with values: +, -, *, / and %. Integer division discards the fractional part. The remainder helps divide queue tokens into groups.','int groups = 17 / 5; // 3\nint remaining = 17 % 5; // 2\ndouble average = 17 / 5.0; // 3.4','A fixed number of arithmetic operations takes O(1) time and space.','Calculate total and average marks','For marks 71, 82 and 90, print total 243 and average 81.0. Also test an average with a fractional part.','Use a decimal operand in the division to preserve the fractional part.'],
['input','Input & output',1,'Input lets a user supply values while a program runs. Scanner reads values; System.out.println displays them.','Scanner input = new Scanner(System.in);\nint count = input.nextInt();\nSystem.out.println("Count: " + count);','A fixed number of bounded integers takes O(1) time and space in the interview model. General text input depends on length.','Read and print three integers','Read three integers and print each on its own line. Test 8, 15, 23, then test zero and negative values.','Import java.util.Scanner. Use one Scanner and read each value with nextInt().'],
['conditions','Conditions & decisions',1,'An if statement chooses code based on a true-or-false condition. Use else for another outcome. A dashboard can warn when feed stock is low.','if (feedBags < 5) {\n    System.out.println("Restock");\n} else {\n    System.out.println("Stock is sufficient");\n}','A fixed if/else decision takes O(1) time and space.','Classify an integer','Print positive, negative or zero for an integer. Test 12, -3 and 0.','Consider n > 0, n < 0, and the remaining case.'],
['loops','Loops',1,'A loop repeats code. Use a for loop when the repetitions are known, such as printing a sequence of queue tokens.','for (int token = 1; token <= 4; token++) {\n    System.out.println(token);\n}','n constant-time iterations take O(n) time and O(1) auxiliary space.','Sum numbers from 1 to n','For n = 5, return 15. Test n = 0 and n = 1. Start with a loop, then consider a formula.','Keep a running total. Consider n × (n + 1) / 2 only after your loop works.'],
['arrays','Arrays',1,'An array stores a fixed-size sequence of one type. Indices start at zero. Daily farm counts can be kept in an int array.','int[] counts = {10, 14, 12};\nSystem.out.println(counts[0]);\nSystem.out.println(counts.length);','Index access is O(1). Traversal is O(n). Input storage is O(n).','Find the largest element','For [4, 9, 2, 7], return 9. Test a one-element array and negative values. Assume a nonempty input.','Initialize the candidate from an actual array element, not zero.'],
['strings','Strings',1,'String stores immutable text. Use charAt to inspect characters and equals to compare content.','String name = "Java";\nchar first = name.charAt(0);\nboolean same = name.equals("Java");','charAt is O(1). Content equality is O(n) in the worst case.','Count vowels','For "Placement", return 3. Treat uppercase and lowercase vowels alike. Test an empty string.','Visit each character and check whether it is a vowel.'],
['methods','Methods',1,'A method groups reusable behavior, accepts parameters and can return a result. Small methods are easier to explain and test.','static int square(int value) {\n    return value * value;\n}','This multiplication takes O(1) time and auxiliary space.','Write an isEven method','Return true for 8 and false for 7. Test zero and a negative even number.','Use the remainder after division by 2.'],
['oop','Object-oriented programming',1,'OOP groups data and behavior in classes. Encapsulation controls access to state. Inheritance and interfaces support reuse and different implementations.','class Counter {\n    private int value;\n    void increment() { value++; }\n    int getValue() { return value; }\n}','The getter and increment are O(1). Each Counter stores O(1) state.','Model a bank account','Create a class with a private balance, deposit and getter. Reject nonpositive deposits.','Validate state changes in the method that changes the balance.'],
['arraylist','ArrayList',1,'ArrayList is a resizable indexed list. Use it for a sequence that grows, such as farm visits.','ArrayList<String> visits = new ArrayList<>();\nvisits.add("Morning");\nSystem.out.println(visits.get(0));','get is O(1). Append is amortized O(1). Middle insertion is O(n). Storage is O(n).','Filter even numbers','From [1, 2, 4, 7, 8], return [2, 4, 8] in the same order.','Add an element to a new list only when it passes the condition.'],
['hashmap','HashMap',1,'A HashMap associates unique keys with values. Use it for fast lookups and counts.','Map<String, Integer> counts = new HashMap<>();\ncounts.put("OP", 3);\nint count = counts.getOrDefault("ER", 0);','get/put are average O(1). Storage is O(n). Worst cases depend on collisions.','Count word frequencies','For ["java", "sql", "java"], return java: 2 and sql: 1.','Update a word’s previous count plus one.'],
['hashset','HashSet',1,'A HashSet stores unique values and supports membership checks, such as recording distinct visitor IDs.','Set<Integer> ids = new HashSet<>();\nids.add(12);\nboolean seen = ids.contains(12);','add/contains are average O(1), with O(n) total storage.','Detect duplicates','Return true for [2, 4, 2] and false for [2, 4, 7].','Check whether each value has already been seen.'],
['collections','Collections framework',1,'List, Set, Map and Queue offer different ways to manage groups of values. Choose based on the operations you need.','List<Integer> list = new ArrayList<>();\nSet<Integer> set = new HashSet<>();\nQueue<Integer> queue = new ArrayDeque<>();','Complexity depends on implementation. ArrayDeque end operations are amortized O(1).','Sort unique IDs','For [4, 1, 4, 2, 1, 3], print 1 2 3 4. Test an empty list and repeated IDs.','Decide whether order, uniqueness or key lookup matters most.'],
['complexity','Time & space complexity',1,'Complexity describes how work and memory grow with the input. O(n) does not mean n seconds.','for (int x : values) {\n    System.out.println(x);\n}','This traversal is O(n) time and O(1) auxiliary space, excluding input and output.','Count nested-loop operations','For n = 3, two n-iteration nested loops perform 9 inner operations. Calculate the count directly; use long for large n.','Count how often the innermost operation runs.'],
['sorting','Sorting',2,'Sorting places values in order. Learn insertion sort before merge sort. Sorted values simplify many searches.','int[] values = {8, 3, 5};\nArrays.sort(values);','Insertion sort is O(n²) worst-case time, O(1) space. Standard merge sort is O(n log n) time, O(n) space.','Implement insertion sort','Sort [5, 2, 4, 1]. Test already sorted input and duplicates.','Maintain a sorted prefix; insert the next value into it.'],
['binary-search','Binary search',2,'Binary search repeatedly halves a sorted search range. It requires ordered data or a monotonic condition.','int mid = left + (right - left) / 2;\n// Compare the middle value and keep one half.','Iterative binary search is O(log n) time and O(1) auxiliary space.','Search a sorted array','Find target 7 in [1, 3, 7, 9]. Return -1 for an absent target.','After each comparison, discard the half that cannot contain the target.'],
['two-pointers','Two pointers',2,'Two pointers track two positions in a sequence to avoid unnecessary comparisons.','int left = 0;\nint right = values.length - 1;','A scan with at most n moves per pointer is O(n) time and O(1) space.','Reverse an array in place','Transform [1, 2, 3, 4] into [4, 3, 2, 1] without another array.','Swap the ends, then move inward.'],
['sliding-window','Sliding window',2,'A sliding window maintains information about a contiguous range, reusing work as its boundaries move.','windowSum += incoming;\nwindowSum -= outgoing;','A fixed-window sum scan is O(n) time and O(1) auxiliary space.','Maximum sum of k consecutive values','For [2, 1, 5, 1, 3, 2] and k = 3, return 9. Assume 1 ≤ k ≤ n.','Compute the first window, then remove its outgoing value and add the next.'],
['prefix-sum','Prefix sum',2,'Prefix sums store totals through each boundary, allowing fast range-sum queries after preprocessing.','int[] prefix = new int[values.length + 1];\n// prefix[i + 1] is the sum through index i.','Preprocessing is O(n) time and space. Range-sum queries are O(1).','Running sum of an array','For [1, 2, 3, 4], return [1, 3, 6, 10].','Keep a total of the values seen so far.'],
['hashing','Hashing patterns',2,'Hashing enables fast membership and key lookup. Maps and sets are useful for pairs, complements and frequencies.','Map<Integer, Integer> indices = new HashMap<>();\nindices.put(8, 0);','A one-pass map search is average O(n) time and O(n) space.','Two-sum indices','For [2, 7, 11, 15] and target 9, return [0, 1]. Assume one answer; do not reuse an element.','Look for the complement target minus the current value among earlier values.'],
['linked-list','Linked List',3,'A linked list connects value-containing nodes using references.','class Node {\n    int value;\n    Node next;\n}','Traversal is O(n) time, O(1) auxiliary space. Index access is O(n).','Count linked-list nodes','Count nodes in 4 → 8 → 12. Return 0 for an empty list.','Follow next references until null.'],
['stack','Stack',3,'A stack returns the most recently added item first. It models undo behavior. Use Deque for a Java stack.','Deque<Integer> stack = new ArrayDeque<>();\nstack.push(4);\nint latest = stack.pop();','push/pop are amortized O(1); storing n items uses O(n) space.','Validate parentheses','Return true for "(())" and false for "(()". Begin with round brackets only.','Each closing bracket must have an available opening bracket.'],
['queue','Queue',3,'A queue serves the earliest added item first, like an ordinary token queue.','Queue<Integer> queue = new ArrayDeque<>();\nqueue.offer(101);\nInteger first = queue.poll();','ArrayDeque offer/poll are amortized O(1). Storage is O(n).','Simulate a token queue','Add 101, 102, 103. Serve two and print who is next. Handle an empty queue.','offer adds, poll serves and peek observes the next item.'],
['recursion','Recursion',3,'A recursive method solves a smaller version of its own problem. A base case stops further calls.','static void countdown(int n) {\n    if (n <= 0) return;\n    System.out.println(n);\n    countdown(n - 1);\n}','This countdown takes O(n) time and O(n) call-stack space.','Recursive sum from 1 to n','For n = 4, return 10. Define n = 0.','Combine n with the smaller answer for n − 1.'],
['trees','Trees',4,'A tree is connected and has no cycles. A binary-tree node has at most two children.','class TreeNode {\n    int value;\n    TreeNode left, right;\n}','Traversal is O(n) time. Recursive depth uses O(h) space for height h.','Count binary-tree nodes','Return 0 for an empty tree, 1 for a leaf and 3 for a root with two leaves.','Count the current node and its two subtrees.'],
['bst','Binary Search Trees',4,'In a BST with distinct keys, smaller values lie to the left and larger ones to the right.','// Compare target with node.value.\n// Follow left for smaller, right for larger.','Search is O(h): O(log n) if balanced, O(n) if skewed.','Search a BST','Check whether a target exists. Test the root, a missing value and an empty tree.','Only one subtree can contain the target after each comparison.'],
['tree-dfs','Tree DFS',4,'Depth-first search explores a branch before returning to other branches. Use recursion or a stack.','Deque<TreeNode> pending = new ArrayDeque<>();','DFS is O(n) time and O(h) recursive space.','Maximum tree depth','Return 0 for an empty tree and 1 for a leaf. Test a single long branch.','Use the larger of the two subtree depths.'],
['tree-bfs','Tree BFS',4,'Breadth-first search visits one level at a time, using a queue.','Queue<TreeNode> pending = new ArrayDeque<>();','BFS is O(n) time and O(w) space for maximum width w.','Print tree levels','For root 1 with children 2 and 3, return levels [1] and [2, 3].','Remember the queue size at the start of each level.'],
['traversals','Tree traversal',4,'Preorder: root, left, right. Inorder: left, root, right. Postorder: left, right, root.','// The position of the visit operation\n// determines the traversal order.','Each traversal is O(n) time and O(h) recursive space, excluding output.','Implement inorder traversal','For root 2 with children 1 and 3, return [1, 2, 3].','Visit the current node between visiting its left and right subtrees.'],
['heap','Heap / PriorityQueue',5,'A heap efficiently exposes a priority item. Java PriorityQueue is a min-heap by default.','PriorityQueue<Integer> scores = new PriorityQueue<>();\nscores.offer(8);\nscores.offer(3);\nint smallest = scores.peek();','offer/poll are O(log n), peek is O(1). Storage is O(n).','Find the kth largest value','For [3, 2, 1, 5, 6, 4] and k = 2, return 5.','Keep the largest k values seen in a min-heap of size k.'],
['greedy','Greedy algorithms',5,'Greedy algorithms make local choices. You must justify that those choices produce a global optimum.','// Choose a candidate and explain why\n// the choice preserves an optimal solution.','Problem dependent. Sorting followed by a scan is often O(n log n).','Select non-overlapping meetings','Choose the maximum number of compatible intervals. Test equal ending times.','Compare choosing the meeting that finishes earliest with other rules.'],
['graphs','Graphs',5,'Graphs connect vertices using edges. An adjacency list stores each vertex’s neighbors.','List<List<Integer>> graph = new ArrayList<>();\ngraph.add(new ArrayList<>());','Adjacency-list storage is O(V + E). Traversal is O(V + E).','Build an undirected adjacency list','Use edges (0,1), (1,2), (0,2). Print each vertex’s neighbors.','Store each undirected edge in both endpoints’ lists.'],
['graph-traversal','Graph BFS / DFS',5,'Track visited vertices to handle cycles. BFS finds shortest paths by edge count in an unweighted graph.','boolean[] visited = new boolean[vertexCount];\nQueue<Integer> pending = new ArrayDeque<>();','BFS/DFS is O(V + E) time and O(V) auxiliary space with adjacency lists.','Check whether a path exists','Test a cyclic graph with one disconnected vertex.','Mark vertices visited when adding them to pending work.'],
['union-find','Union Find',5,'Union Find tracks connected groups. find locates a representative; union merges groups.','int[] parent = new int[n];\nfor (int i = 0; i < n; i++) parent[i] = i;','Path compression and union by rank/size give amortized O(α(n)) operations and O(n) space.','Detect an undirected cycle','Process (0,1), (1,2), (2,0). Identify the edge joining already connected vertices.','Compare representatives before merging endpoints.'],
['dp','Dynamic Programming',6,'DP saves answers to overlapping subproblems. Define a state, base cases and transition first.','// State: what does dp[i] mean?\n// Base: which answers are already known?\n// Transition: which smaller answers are needed?','Time is states × work per state. Space depends on retained states.','Minimum cost to climb stairs','For costs [10, 15, 20], the minimum cost to reach beyond the last stair is 15. Define the state and avoid repeated work.','Each distinct input needs to be solved only once.'],
['fibonacci','Fibonacci pattern',6,'A Fibonacci value depends on the previous two. Practise memoization, tabulation and rolling state.','// F(0) = 0; F(1) = 1\n// F(n) = F(n - 1) + F(n - 2)','Tabulation: O(n) time and space. Rolling state: O(n) time and O(1) space.','Compute Fibonacci','Return F(6) = 8. Test 0 and 1. Assume n ≤ 40 for int output.','Begin from the two base values and work toward n.'],
['climbing','Climbing stairs',6,'Count ways to climb using moves of one or two steps, combining answers for earlier steps.','// Consider the final move into step i.','Rolling state is O(n) time and O(1) auxiliary space.','Count staircase paths','For 3 steps, return 3. Test 1 and 2 steps.','The last move came from one step earlier or two steps earlier.'],
['knapsack','0/1 Knapsack',6,'Choose each item at most once, staying within capacity while maximizing value.','// Compare skipping an item with taking it\n// when enough capacity remains.','Classic DP is O(nW) time and space. One-dimensional DP uses O(W) space.','Maximize packed value','Weights [1,3,4], values [15,20,30], capacity 4: return 35.','In a one-dimensional solution, process capacity downward to avoid reusing items.'],
['subset','Subset sum',6,'Subset sum asks whether some nonnegative values can total a target, with each item used at most once.','// dp[s] means sum s is reachable.','Standard DP is O(nT) time and O(T) optimized space for target T.','Find a target subset','For [3,7,2], target 9 is possible. Test an unreachable target.','Start from sum zero and update without using an item twice.'],
['lis','Longest increasing subsequence',6,'A subsequence preserves order while allowing skipped elements. Find the longest strictly increasing one.','// dp[i] can mean LIS length ending at i.','Introductory DP: O(n²) time, O(n) space. A tails approach achieves O(n log n) time.','Find LIS length','For [10,9,2,5,3,7], return 3. Test duplicates and descending input.','For each position, inspect smaller values at earlier positions.'],
['grid-dp','Grid DP',6,'Build cell answers from neighboring cells according to the allowed moves.','// With right/down movement, consider\n// the cell above and the cell to the left.','For r rows and c columns: O(rc) time, O(rc) space, or O(c) with rolling rows.','Count unique grid paths','A 3 × 2 grid has 3 right/down routes from top-left to bottom-right.','An interior cell can be reached from above or from its left.'],
];
export const lessons:Lesson[]=rows.map(([id,title,phase,definition,exampleCode,complexity,problem,example,hint])=>({id,title,phase,definition,exampleCode,complexity,problem,example,hint}));
export const phases=[{name:'Build your foundation',caption:'Java essentials & core collections',level:'Beginner'},{name:'Recognize the patterns',caption:'Searching, sorting & array techniques',level:'Easy'},{name:'Think in structures',caption:'Lists, stacks, queues & recursion',level:'Easy → Medium'},{name:'Branch out',caption:'Trees & traversal',level:'Easy → Medium'},{name:'Connect the dots',caption:'Heaps, greedy & graphs',level:'Medium'},{name:'Solve with dynamic programming',caption:'States, transitions & classic patterns',level:'Medium'}];
export const placementTopics=[
{name:'Projects & weekly review',short:'Projects',concept:'Your project in 60 seconds',definition:'Explain the problem, your role, the main data flow and one implemented outcome. Use a concrete example. Describe what you personally built.',question:'Tell me about FlockSense. What did you personally implement?'},
{name:'Aptitude',short:'Aptitude',concept:'Percentages',definition:'Percentage means a number out of 100. 15% of 200 is 30. For percentage increase, divide the increase by the original value and multiply by 100.',question:'A value increases from 80 to 100. What is the percentage increase?'},
{name:'Database Management',short:'DBMS',concept:'Primary and foreign keys',definition:'A primary key uniquely identifies a row and cannot be null. A foreign key references a key in another table. A visit row can reference its farm.',question:'How do primary and foreign keys differ?'},
{name:'Operating Systems',short:'OS',concept:'Processes vs. threads',definition:'A process is a running program with its own address space. Threads are execution paths within a process. They share process memory but have separate stacks. Shared data needs coordination.',question:'What is the difference between a process and a thread?'},
{name:'Computer Networks',short:'Networks',concept:'TCP vs. UDP',definition:'TCP provides a reliable, ordered byte stream. UDP sends datagrams without guaranteeing delivery or order. An application can add its own reliability on top of UDP.',question:'Why might an application choose UDP rather than TCP?'},
{name:'Java & OOP interviews',short:'Java / OOP',concept:'Encapsulation',definition:'Encapsulation groups state with the operations that manage it. Private fields and validated methods help preserve rules, such as a nonnegative account balance.',question:'Why use a private field if a public getter can read it?'},
{name:'SQL practice',short:'SQL',concept:'SELECT and WHERE',definition:'SELECT chooses columns. WHERE keeps matching rows. Example: SELECT name FROM farms WHERE bird_count > 100; Predict the output and test the boundary.',question:'Write a query returning names of farms with more than 100 birds.'},
];
export const projectItems=['Problem statement & users','Your personal contribution','Architecture & data flow','Frontend & key screens','Backend & APIs','Database & schema','Algorithms used','AI / ML components','Novelty & alternatives','Challenges & trade-offs','Impact & evidence','Future improvements'];
export const steps=['Understand the problem','Find a brute-force approach','Calculate its complexity','Consider an optimization','Write Java code','Test examples & edge cases','State final time & space'];
export const blocks=[{id:'revision',name:'Warm up your memory',label:'Revision',minutes:10,color:'purple'},{id:'learn',name:'Learn one thing well',label:'Learn',minutes:15,color:'green'},{id:'code',name:'Turn knowledge into code',label:'Practice',minutes:25,color:'blue'},{id:'placement',name:'Get interview ready',label:'Placement',minutes:10,color:'orange'}];
export const taskIds=['revision-0','revision-1','learn-0','learn-1','learn-2','code-0','code-1','placement-0','placement-1'];
export type Session={date:string;topicId:string;checks:string[];steps:string[];code:string;explanation:string;notes:string;revision:string;attempted:number;solved:number;independent:number;topicDone:string;p1:string;p2:string;hintUsed:boolean;reported:boolean;judge?:import('./judge-types').JudgeSummary;complexity?:{time:string;space:string};};
export type StudyState={currentTopic:string;mastered:string[];sessions:Record<string,Session>;practice?:Record<string,Session>;projects:Record<string,string[]>;projectNotes:Record<string,string>;};
export const initialState=():StudyState=>({currentTopic:'variables',mastered:[],sessions:{},projects:{flocksense:[],flowpulse:[]},projectNotes:{flocksense:'',flowpulse:''}});
export const newSession=(date:string,topicId:string):Session=>({date,topicId,checks:[],steps:[],code:'',explanation:'',notes:'',revision:'',attempted:0,solved:0,independent:0,topicDone:'',p1:'',p2:'N/A',hintUsed:false,reported:false});
export function localDate(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function dateFromKey(key:string){return new Date(`${key}T12:00:00`);}
export function isComplete(session:Session){return taskIds.every(id=>session.checks.includes(id));}
