import {B,M,S,C,D,type Question} from './types';

export const aptitudeQuestions: Record<string,Question[]> = {
  percentages:B([
    M('What is 15% of 200?', ['15','20','30','45'],2,'15/100 × 200 = 30.'),
    S('Express 3/8 as a percentage.', '37.5%, because 3÷8×100=37.5.'),
    S('18 students in a class of 60 join a club. What percentage joins?', '30%. Divide the part 18 by the whole 60 and multiply by 100.'),
    C('A practice score rises from 40 to 50. Calculate the percentage increase and identify the denominator.', '25%, using (50−40)/40×100. The original score, 40, is the denominator.'),
    M('A price increases by 20% and then decreases by 20%. Relative to the original price, it is:', ['Unchanged','4% lower','4% higher','20% lower'],1,'The multiplier is 1.2×0.8=0.96. The second percentage uses the increased base.'),
    S('After a 25% discount, an item costs 900. What was the original price?', '1,200. The paid price is 75% of the original, so 900/0.75=1,200.'),
    C('A class pass rate improves from 60% to 75%. Report both the percentage-point change and the relative percentage increase.', 'It rises by 15 percentage points and by 25% relative to the original rate: (75−60)/60×100. These are different measurements.'),
    C('A price falls by 30%. What percentage increase from the reduced price restores the original price?', 'About 42.86%. Starting at 100 gives 70; restoring 30 requires 30/70×100, not 30%.'),
    D('Team A’s success rate is 80% over 50 attempts; Team B’s is 60% over 150 attempts. Evaluate a claim that their combined success rate is 70%.', 'The claim ignores unequal counts. Successes are 40+90=130 from 200 attempts, so the combined rate is 65%. A simple average of percentages is appropriate here only with equal denominators.'),
    C('A store wants its final price to be 20% above cost after a 25% discount from the marked price. By what percentage above cost must it mark the item?', '60%. Let cost=100; desired selling price=120. Marked price must be 120/0.75=160. Check that a 25% discount on 160 gives 120.'),
  ]),
  ratio:B([
    M('Simplify the ratio 18:24.', ['2:3','3:4','4:3','6:8 only'],1,'Divide both terms by their greatest common divisor, 6, to get 3:4.'),
    S('Share 150 in the ratio 2:3.', '60 and 90. There are five equal ratio units, each worth 30.'),
    S('If a:b=4:5 and a=20, what is b?', '25. Each ratio unit equals 5.'),
    C('If A:B=2:3 and B:C=4:5, find A:B:C.', '8:12:15. Scale the first ratio by 4 and the second by 3 so that both have B=12.'),
    M('A drink has milk:water = 3:2 and total volume 20 L. How much milk is present?', ['8 L','10 L','12 L','15 L'],2,'Milk is 3/5 of the total, or 12 L.'),
    S('Six identical machines produce 240 units per hour. At the same independent rate, how many units do nine machines produce per hour?', '360. Each machine produces 40 units per hour, so 9×40=360. The direct proportion assumes unchanged machine rates.'),
    C('A and B are aged in the ratio 3:5, and their ages sum to 64. What will their age ratio be after 8 years?', 'Current ages are 24 and 40. After 8 years they are 32 and 48, ratio 2:3. Adding equal amounts does not preserve the original ratio.'),
    C('Mix a 20% salt solution and a 50% salt solution to obtain 12 L of 30% solution, assuming volumes add. Find the volume of each.', '8 L of the 20% solution and 4 L of the 50% solution. Solve x+y=12 and 0.2x+0.5y=3.6; the mixing ratio is 2:1.'),
    D('A team has developers:testers = 4:1. Someone claims doubling the number of testers doubles the total team. Evaluate using a ratio-unit model.', 'Originally there are five units. Doubling testers changes 4:1 to 4:2 and total units from 5 to 6, a 20% increase. The unchanged developer count prevents the total from doubling.'),
    C('Container A holds milk:water = 3:1 and B holds 1:1. Mix 8 L from A with x L from B to obtain milk:water = 2:1. Find x.', 'x=4 L. A contributes 6 L milk and 2 L water; B contributes x/2 of each. Solve (6+x/2)/(2+x/2)=2, giving x=4. The final mixture has 8 L milk and 4 L water.'),
  ]),
  average:B([
    M('What is the arithmetic mean of 4, 6, and 8?', ['4','5','6','8'],2,'The total is 18; dividing by three gives 6.'),
    S('Five scores have an average of 12. What is their total?', '60, using total=count×average.'),
    S('The average of 10 and x is 14. Find x.', '18. Their total must be 28, so x=28−10.'),
    C('The average of six scores is 20. A seventh score of 34 is added. Find the new average.', '22. Original total=120, new total=154, and 154/7=22.'),
    M('If every value in a dataset increases by 5, its arithmetic mean:', ['Stays unchanged','Increases by 5','Multiplies by 5','Increases by 5 divided by the count'],1,'The total increases by 5 times the count, so dividing by the same count adds 5 to the mean.'),
    S('Group A has 10 students averaging 70; Group B has 20 averaging 85. Find the combined average.', '80, because (10×70+20×85)/30=2,400/30. Weight each group by its size.'),
    C('The average of eight values was reported as 15 because 28 was entered as 12. Correct the average.', '17. The total was 16 too low, so the mean rises by 16/8=2.'),
    C('A five-value moving average is 18. The oldest value 10 leaves and a new value x arrives, raising the average to 22. Find x.', '30. The total rises from 90 to 110, so x−10=20.'),
    D('Response times in milliseconds are 10,10,10,10,160. Compare mean and median and evaluate which alone best communicates typical versus worst-user experience.', 'Mean=40 and median=10. The median describes the middle experience; the mean reflects the slow outlier more strongly. Neither alone captures all experience—report a distribution or tail measure with sample size, rather than hiding the 160 ms case.'),
    C('Twelve employees have average age 30. Three leave with average age 26, and five join with average age 34. Find the new average age.', '32 2/7 years, approximately 32.29. Total becomes 12×30−3×26+5×34=452 across 14 employees; 452/14=32 2/7.'),
  ]),
  profit:B([
    M('An item costs 500 and sells for 600. What is the profit?', ['50','100','500','1,100'],1,'Profit=selling price−cost price=100.'),
    S('An item bought for 800 sells for 720. What is the loss percentage, using cost as the base?', '10%, since loss=80 and 80/800×100=10.'),
    S('What is the selling price of an item costing 250 at a 20% profit on cost?', '300. Add 20% of 250, which is 50.'),
    C('A marked price is 1,000, a discount is 10%, and cost is 750. Find selling price and profit percentage on cost.', 'Selling price=900. Profit=150, which is 150/750×100=20%.'),
    M('A profit of 20 on cost 80 gives which profit percentage on cost?', ['20%','25%','80%','16%'],1,'20/80×100=25%. Dividing by selling price would instead calculate margin, a different quantity.'),
    S('An item sells for 660 at a 10% profit on cost. Find its cost.', '600, because 660/1.10=600.'),
    C('A seller buys an item for 400 and spends 100 repairing it before selling it for 600. Include repairs in cost and find profit percentage.', 'Total cost=500, profit=100, profit percentage=20%. Ignoring the repair expense would overstate profit.'),
    C('Two items each sell for 600. One earns 20% profit on cost and the other incurs 20% loss on cost. Find the combined result.', 'Costs are 600/1.2=500 and 600/0.8=750, total 1,250. Revenue=1,200; loss=50 or 4% of total cost. Equal selling prices do not imply equal costs.'),
    D('A merchant advertises “20% off, then another 10% off.” Compare the final price with a single 30% discount and explain the difference.', 'Successive discounts multiply: 0.8×0.9=0.72, a 28% discount. A single 30% discount gives 0.70 of marked price. The second 10% is taken from the reduced amount.'),
    C('A batch of 100 items costs 50 each. Ten become unsellable with no salvage value. What selling price per remaining item gives 20% profit on the entire batch cost?', 'Total cost=5,000; target revenue=6,000. Divide by 90 sellable items: 66 2/3 per item. If prices must be whole currency units, at least 67 is needed to meet or exceed the target.'),
  ]),
  work:B([
    M('A worker finishes one job in 5 days at a constant rate. What fraction is completed per day?', ['5','1/5','1/2','1/10'],1,'Rate is one job divided by five days, or 1/5 job per day.'),
    S('Two identical workers each need 8 days alone. If their rates add without interference, how long do they need together?', '4 days. Their combined rate is 1/8+1/8=1/4 job per day.'),
    S('At a constant rate of 1/6 job per day, how much work is completed in 2 days?', '1/3 of the job, using rate×time.'),
    C('A completes a job in 12 days and B in 18 days. How long will they take together at constant independent rates?', '36/5=7.2 days. Combined rate=1/12+1/18=5/36 job per day.'),
    M('A is twice as efficient as B on the same job. If B takes 10 days, A takes:', ['20 days','10 days','5 days','2 days'],2,'Time is inversely proportional to rate for a fixed amount of work.'),
    S('Six equal workers finish a job in 10 days. How long would fifteen equal workers take, assuming perfectly additive rates?', '4 days. The job requires 60 worker-days; 60/15=4.'),
    C('A takes 10 days alone and B takes 15. They work together for 3 days, then A leaves. How much longer does B need?', 'Together they complete 3×(1/10+1/15)=1/2. B takes (1/2)/(1/15)=7.5 additional days.'),
    C('A tank fills in 6 hours from one pipe, while a drain empties a full tank in 9 hours, both at constant rates. Starting empty with both open, how long to fill?', '18 hours. Net rate=1/6−1/9=1/18 tank per hour. This relies on constant rates and the drain not emptying more water than is present.'),
    D('A manager assumes doubling programmers always halves delivery time because work rates add. Evaluate this model for a software project.', 'The arithmetic assumes divisible independent work, equal productivity, no onboarding, and no coordination overhead. Software has dependencies and communication costs, so identify parallelizable work and measure bottlenecks before using the model.'),
    C('A takes 6 days alone and B takes 12. They alternate full workdays starting with A, stopping as soon as the job is done. Find total time.', 'Each two-day cycle completes 1/6+1/12=1/4. After 6 days, 3/4 is done; day 7 by A reaches 11/12, and B finishes the last 1/12 on day 8. Total 8 days.'),
  ]),
  speed:B([
    M('A car travels 180 km in 3 hours at constant speed. Its speed is:', ['30 km/h','60 km/h','90 km/h','540 km/h'],1,'Speed=distance/time=180/3=60 km/h.'),
    S('Convert 54 km/h to meters per second.', '15 m/s, multiplying by 5/18.'),
    S('How long does a cyclist at 20 km/h need to cover 50 km?', '2.5 hours, or 2 hours 30 minutes, using time=distance/speed.'),
    C('Travel 60 km at 30 km/h and the next 60 km at 60 km/h. Find average speed for the entire trip.', '40 km/h. Total distance=120 km; time=2+1=3 hours. The simple mean 45 is wrong because travel times differ.'),
    M('Two runners move toward each other at 8 and 12 km/h on a straight road. Their closing speed is:', ['4 km/h','10 km/h','20 km/h','96 km/h'],2,'Opposite-direction closing speeds add: 8+12=20 km/h.'),
    S('A 150 m train moves at 15 m/s. How long does it take to completely pass a fixed pole?', '10 seconds. The train must move its entire length past the pole.'),
    C('A 120 m train crosses a 180 m platform at 54 km/h. How long from its front entering to its rear leaving?', '20 seconds. Required distance=120+180=300 m; speed=15 m/s; time=300/15.'),
    C('A boat moves at 10 km/h in still water; the stream is 2 km/h. It travels 24 km downstream and 24 km upstream. Find total time and average speed.', 'Downstream speed=12, upstream=8. Times are 2 and 3 hours; total 5 hours, average speed=48/5=9.6 km/h.'),
    D('GPS samples report speeds of 20 and 60 km/h. Under what sampling assumptions would 40 km/h be the correct trip average, and when would it be wrong?', 'It is correct if those speeds each apply for equal durations and there is no omitted travel/stopping time. Equal-distance legs require total distance/total time and yield 30 km/h. Isolated readings alone do not determine the full-trip average.'),
    C('A bus leaves at 09:00 at 40 km/h. A car follows the same route at 10:00 at 60 km/h. Assuming constant speeds and no stops, when does the car catch it and how far from the start?', 'The bus has a 40 km lead. Closing speed=20 km/h, so catch-up takes 2 hours after 10:00: noon, 120 km from the start.'),
  ]),
  probability:B([
    M('For one fair six-sided die, what is the probability of rolling a 6?', ['1/2','1/3','1/6','5/6'],2,'One of six equally likely outcomes is favorable.'),
    S('What are the probabilities of an impossible event and a certain event?', '0 and 1 respectively. Every probability lies between them.'),
    S('Two independent fair coins are tossed. What is the probability of exactly one head?', '1/2. The equally likely outcomes are HH, HT, TH, TT; HT and TH qualify.'),
    C('A bag contains 3 red and 2 blue balls. Draw two without replacement. Find the probability both are red.', '3/5×2/4=3/10. The second draw’s probabilities change because the first ball is not replaced.'),
    M('For independent events A and B with probabilities 0.4 and 0.5, P(A and B) is:', ['0.9','0.2','0.1','0.45'],1,'Independence permits multiplication: 0.4×0.5=0.2.'),
    S('Find the probability of at least one 6 in two independent fair die rolls.', '1−(5/6)²=11/36. The complement is no 6 on either roll.'),
    C('In a class, 40% study Java, 30% study Python, and 10% study both. What percentage studies at least one?', '60%. Use P(J∪P)=P(J)+P(P)−P(J∩P)=40%+30%−10%.'),
    C('1% of manufactured parts are defective. A check flags 90% of defective parts and 5% of good parts. Among flagged parts, what fraction are defective? Use 10,000 parts to reason.', 'There are 100 defective parts, of which 90 are flagged; 9,900 good parts yield 495 false flags. Thus 90/(90+495)=2/13≈15.38% of flagged parts are defective. The low base rate matters.'),
    D('A candidate says disjoint events are independent because they never occur together. Evaluate this for two disjoint events with positive probability.', 'They are not independent: P(A∩B)=0, but P(A)P(B)>0. Knowing A occurred makes B impossible. Independence and mutual exclusion describe different relationships.'),
    C('A fair die is rolled until the first 6. Derive the expected number of rolls using a recurrence rather than listing infinitely many outcomes.', 'Let E be the expectation. One roll is always used; with probability 5/6 the process restarts, so E=1+(5/6)E, giving E=6. Independent identical rolls justify the restart argument.'),
  ]),
  logical:B([
    M('Assuming a constant difference, what follows 4, 7, 10, 13?', ['14','15','16','18'],2,'Each term increases by 3, so the next is 16.'),
    S('All roses in a garden are flowers. A plant is a rose in that garden. What follows?', 'It is a flower. Apply the stated universal rule to the identified member.'),
    S('If a statement P is true, what is the truth value of “not P”?', 'False. Negation reverses the truth value of the statement.'),
    C('All backend trainees know Java. Riya knows Java. Does it necessarily follow that Riya is a backend trainee? Explain.', 'No. Knowing Java is required of those trainees, but other people may also know it. This incorrectly reverses a one-way implication.'),
    M('Exactly one of P and Q is true. Which combination satisfies the condition?', ['P=true, Q=true','P=false, Q=false','P=true, Q=false','All combinations'],2,'Exclusive OR requires one true statement and one false statement.'),
    S('Four people A,B,C,D stand in a row. A is immediately before B, C is at the left end, and D is at the right end. Determine the order.', 'C,A,B,D. The two middle positions must be occupied by the A,B block.'),
    C('Tasks obey A before C, B before C, and C before D. Give all valid task orders when each task occurs exactly once.', 'A,B,C,D and B,A,C,D. A and B may swap; both precede C, which precedes D.'),
    C('A box has either a red or blue ball, but not both. Label 1 says “The ball is red.” Label 2 says “Label 1 is false.” Exactly one label is true. Can you determine the color?', 'No. If red, label 1 is true and label 2 false; if blue, the reverse holds. Both colors satisfy exactly-one-true, so the information is insufficient.'),
    D('A hiring dataset shows that candidates who took a course have higher placement rates. What additional information is needed before claiming the course caused the increase?', 'Consider prior skill, motivation, selection effects, sample sizes, and comparable control groups. Random assignment or a defensible causal design would strengthen the claim. Association alone does not rule out confounding.'),
    C('A system must satisfy P implies Q, Q implies not R, and R is true. Determine P and Q if all three rules hold, and justify each step.', 'Q must be false; otherwise it would imply not R, contradicting R. P must then be false, since true P would require true Q. The assignment P=false,Q=false,R=true satisfies all rules.'),
  ]),
};
