# Ordered practice progression. The 41 DSA topics retain their existing exercise as Q1.
PROFILES = {
'variables':'add swap area seconds average3 divrem eligibility weightedmean taxdiscount',
'operators':'add divrem ceilgroups max3 sumrange percent ratioequal weightedmean taxdiscount',
'input':'add length total charcategories wordcount gridtotal mean mergesorted postfix',
'conditions':'max3 grade leap eligibility shipping triangle prime median missingpositive',
'loops':'digitcount digitsum factorial reverseint total prefix prime trailingzeros isqrt',
'arrays':'total minimum second sorted zeros rotate equilibrium productexcept kadane',
'strings':'length strreverse palindrome wordcount charcategories normalized compress longunique longpal',
'methods':'max3 digitsum factorial gcd prime lcm power isqrt choose',
'oop':'counter rectangle stockroom payroll cart parking gradebook transfer lending',
'arraylist':'total reverse odd uniqueorder rotate second mergesorted topfrequent missingpositive',
'hashmap':'distinct mode firstunique paircount majority topfrequent subsum longzero consecutive',
'hashset':'distinct uniqueorder union intersection difference consecutive paircount missingpositive topfrequent',
'collections':'minimum reverse mergesorted union topfrequent kthsmall windowdistinct runningmedian rope',
'complexity':'total sorted prefix lowerbound paircount inversions isqrt power missingpositive',
'sorting':'sortdesc minimum second squares mergesorted median inversions topfrequent sortabs',
'binary-search':'lowerbound upperbound occurrences isqrt bstfloor bstceil shipcapacity mindistance kthsmall',
'two-pointers':'palindrome squares zeros mergesorted paircount listpal shortpositive water productexcept',
'sliding-window':'shortpositive windowdistinct windowmin windowmax longunique streamunique longzero subsum circularsum',
'prefix-sum':'total suffix equilibrium paircount subsum productexcept longzero circularsum rangetotal',
'hashing':'distinct firstunique anagram paircount intersection majority longzero subsum consecutive',
'linked-list':'middle minimum reverse pairsswap removenth uniqueorder listpal mergesorted sortdesc',
'stack':'strreverse brackets adjacentcancel postfix nextgreater span longvalid histogram minstack',
'queue':'binaryqueue reversek interleave streamunique bfsorder levelsum windowmax windowmin josephus',
'recursion':'factorial digitsum gcd strreverse palindrome power catalan choose derange',
'trees':'treesum leafcount treemax preorder minheight levelsum balanced diameter maxpath',
'bst':'inorder treemax bstfloor bstceil bstkth validbst balanced diameter maxpath',
'tree-dfs':'treesum leafcount preorder postorder pathsum validbst balanced diameter maxpath',
'tree-bfs':'treewidth levelsum minheight leftview rightview zigzag bstfloor diameter maxpath',
'traversals':'preorder postorder treesum leafcount leftview rightview zigzag validbst pathsum',
'heap':'minimum kthsmall sortdesc topfrequent rope windowmax runningmedian shipcapacity mindistance',
'greedy':'stock ceilgroups sortdesc rope kthsmall shortpositive shipcapacity mindistance wiggle',
'graphs':'degrees components largestcomponent graphdist dfsorder bfsorder bipartite toposort connectnetwork',
'graph-traversal':'bfsorder dfsorder graphdist components largestcomponent islands bipartite toposort connectnetwork',
'union-find':'components largestcomponent componentsizes dynamicgroups redundantedges crosspairs connectnetwork bipartite islands',
'dp':'rob steps13 coinmin partition obstacle lcs edit partitiondiff catalan',
'fibonacci':'lucas fibsum binaryno11 steps13 tribonacci fibonaccieven friends derange tiling4',
'climbing':'steps13 steps123 orderedcoins coinmin obstacle tiling4 binaryno11 friends noadjacenttwos',
'knapsack':'subsetreachable partition subsetcount coinmin coinways partitiondiff unbounded rodcut orderedcoins',
'subset':'subsetcount subsetreachable partition partitiondiff coinways coinmin targetsigns unbounded rodcut',
'lis':'nondec decreasing incsum wiggle bitonic liscount divisiblechain envelopes bridges',
'grid-dp':'gridtotal gridmin gridmax obstacle falling diagonalpath onesquare goldmine gridrectangle',
'percentages':'percent passrate discount changepercent compounddiscount weightedpercent restoreprice taxdiscount population mixture',
'ratio':'ratio ratioequal splitratio fourth splitthree workers weightedmean mixture weightedpercent population',
'average':'average3 mean aboveaverage weightedmean missingmean replaceaverage median averagespeed runningmedian variance',
'profit':'profitamount profitpercent sellingprice costprice discount compounddiscount restoreprice taxdiscount breakeven stock',
'work':'workers worktime remainingwork threerates pipeleak ceilgroups fcfs sjf shipcapacity minstack',
'speed':'distance traveltime units relative averagespeed train boats fcfs shipcapacity mindistance',
'probability':'probability twodice independentprob withoutreplacement atleastone choose binomial paircount catalan derange',
'logical':'eligibility sorted digitcount palindrome ratioequal brackets josephus toposort missingpositive catalan',
'dbms':'distinct uniqueorder mode groupbudget intersection joins stockroom transactions topfrequent lru',
'os':'total prefix fcfs sjf firstfit minstack lru toposort shipcapacity transactions',
'networks':'checksum ipv4 degrees graphdist bfsorder packetorder components toposort connectnetwork lru',
'java-interview':'counter rectangle stockroom payroll cart gradebook brackets transfer lending lru',
'hr':'wordcount length charcategories normalized reversewords firstchar keywordmatch lcs edit compress',
'resume':'wordcount charcategories normalized firstchar keywordmatch reversewords anagram compress lcs edit',
'github':'distinct total sorted uniqueorder prefix longeststreak packetorder toposort lcs edit',
'flocksense':'total mean signcounts aboveaverage mode windowdistinct variance windowmax islands topfrequent',
'flowpulse':'counter total prefix fcfs interleave reversek sjf topfrequent lru shipcapacity',
}
